/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as ReviewDatasetsIndexRouteImport } from './routes/review-datasets.index'
import { Route as EvalIndexRouteImport } from './routes/eval.index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets.index'
import { Route as BenchmarksIndexRouteImport } from './routes/benchmarks.index'
import { Route as TrainingIdRouteImport } from './routes/training.$id'
import { Route as DatasetsDomainRouteImport } from './routes/datasets.$domain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewDatasetsIndexRoute = ReviewDatasetsIndexRouteImport.update({
  id: '/review-datasets/',
  path: '/review-datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalIndexRoute = EvalIndexRouteImport.update({
  id: '/eval/',
  path: '/eval/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksIndexRoute = BenchmarksIndexRouteImport.update({
  id: '/benchmarks/',
  path: '/benchmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIdRoute = TrainingIdRouteImport.update({
  id: '/training/$id',
  path: '/training/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDomainRoute = DatasetsDomainRouteImport.update({
  id: '/datasets/$domain',
  path: '/datasets/$domain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasets/$domain': typeof DatasetsDomainRoute
  '/training/$id': typeof TrainingIdRoute
  '/benchmarks/': typeof BenchmarksIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/eval/': typeof EvalIndexRoute
  '/review-datasets/': typeof ReviewDatasetsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasets/$domain': typeof DatasetsDomainRoute
  '/training/$id': typeof TrainingIdRoute
  '/benchmarks': typeof BenchmarksIndexRoute
  '/datasets': typeof DatasetsIndexRoute
  '/eval': typeof EvalIndexRoute
  '/review-datasets': typeof ReviewDatasetsIndexRoute
  '/training': typeof TrainingIndexRoute
  '/workers': typeof WorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasets/$domain': typeof DatasetsDomainRoute
  '/training/$id': typeof TrainingIdRoute
  '/benchmarks/': typeof BenchmarksIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/eval/': typeof EvalIndexRoute
  '/review-datasets/': typeof ReviewDatasetsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasets/$domain'
    | '/training/$id'
    | '/benchmarks/'
    | '/datasets/'
    | '/eval/'
    | '/review-datasets/'
    | '/training/'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasets/$domain'
    | '/training/$id'
    | '/benchmarks'
    | '/datasets'
    | '/eval'
    | '/review-datasets'
    | '/training'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/datasets/$domain'
    | '/training/$id'
    | '/benchmarks/'
    | '/datasets/'
    | '/eval/'
    | '/review-datasets/'
    | '/training/'
    | '/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetsDomainRoute: typeof DatasetsDomainRoute
  TrainingIdRoute: typeof TrainingIdRoute
  BenchmarksIndexRoute: typeof BenchmarksIndexRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  EvalIndexRoute: typeof EvalIndexRoute
  ReviewDatasetsIndexRoute: typeof ReviewDatasetsIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-datasets/': {
      id: '/review-datasets/'
      path: '/review-datasets'
      fullPath: '/review-datasets/'
      preLoaderRoute: typeof ReviewDatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval/': {
      id: '/eval/'
      path: '/eval'
      fullPath: '/eval/'
      preLoaderRoute: typeof EvalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks/': {
      id: '/benchmarks/'
      path: '/benchmarks'
      fullPath: '/benchmarks/'
      preLoaderRoute: typeof BenchmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$id': {
      id: '/training/$id'
      path: '/training/$id'
      fullPath: '/training/$id'
      preLoaderRoute: typeof TrainingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$domain': {
      id: '/datasets/$domain'
      path: '/datasets/$domain'
      fullPath: '/datasets/$domain'
      preLoaderRoute: typeof DatasetsDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsDomainRoute: DatasetsDomainRoute,
  TrainingIdRoute: TrainingIdRoute,
  BenchmarksIndexRoute: BenchmarksIndexRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  EvalIndexRoute: EvalIndexRoute,
  ReviewDatasetsIndexRoute: ReviewDatasetsIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
