/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ModelsOwnerNameRouteImport } from './routes/models.$owner.$name'
import { Route as ChatOwnerNameRouteImport } from './routes/chat.$owner.$name'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsOwnerNameRoute = ModelsOwnerNameRouteImport.update({
  id: '/models/$owner/$name',
  path: '/models/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatOwnerNameRoute = ChatOwnerNameRouteImport.update({
  id: '/chat/$owner/$name',
  path: '/chat/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/models/': typeof ModelsIndexRoute
  '/chat/$owner/$name': typeof ChatOwnerNameRoute
  '/models/$owner/$name': typeof ModelsOwnerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/models': typeof ModelsIndexRoute
  '/chat/$owner/$name': typeof ChatOwnerNameRoute
  '/models/$owner/$name': typeof ModelsOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/models/': typeof ModelsIndexRoute
  '/chat/$owner/$name': typeof ChatOwnerNameRoute
  '/models/$owner/$name': typeof ModelsOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/models/'
    | '/chat/$owner/$name'
    | '/models/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/models' | '/chat/$owner/$name' | '/models/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/models/'
    | '/chat/$owner/$name'
    | '/models/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  ChatOwnerNameRoute: typeof ChatOwnerNameRoute
  ModelsOwnerNameRoute: typeof ModelsOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$owner/$name': {
      id: '/models/$owner/$name'
      path: '/models/$owner/$name'
      fullPath: '/models/$owner/$name'
      preLoaderRoute: typeof ModelsOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$owner/$name': {
      id: '/chat/$owner/$name'
      path: '/chat/$owner/$name'
      fullPath: '/chat/$owner/$name'
      preLoaderRoute: typeof ChatOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  ChatOwnerNameRoute: ChatOwnerNameRoute,
  ModelsOwnerNameRoute: ModelsOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
