/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ModelsOwnerNameRouteImport } from './routes/models.$owner.$name'
import { Route as ChatOwnerNameRouteImport } from './routes/chat.$owner.$name'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/transparency.lazy').then((d) => d.Route))
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/status.lazy').then((d) => d.Route))
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat.lazy').then((d) => d.Route))
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/catalog.lazy').then((d) => d.Route))
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bench.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/models.index.lazy').then((d) => d.Route))
const ModelsOwnerNameRoute = ModelsOwnerNameRouteImport.update({
  id: '/models/$owner/$name',
  path: '/models/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/models.$owner.$name.lazy').then((d) => d.Route),
)
const ChatOwnerNameRoute = ChatOwnerNameRouteImport.update({
  id: '/$owner/$name',
  path: '/$owner/$name',
  getParentRoute: () => ChatRoute,
} as any).lazy(() =>
  import('./routes/chat.$owner.$name.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bench': typeof BenchRoute
  '/catalog': typeof CatalogRoute
  '/chat': typeof ChatRouteWithChildren
  '/status': typeof StatusRoute
  '/transparency': typeof TransparencyRoute
  '/models/': typeof ModelsIndexRoute
  '/chat/$owner/$name': typeof ChatOwnerNameRoute
  '/models/$owner/$name': typeof ModelsOwnerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bench': typeof BenchRoute
  '/catalog': typeof CatalogRoute
  '/chat': typeof ChatRouteWithChildren
  '/status': typeof StatusRoute
  '/transparency': typeof TransparencyRoute
  '/models': typeof ModelsIndexRoute
  '/chat/$owner/$name': typeof ChatOwnerNameRoute
  '/models/$owner/$name': typeof ModelsOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bench': typeof BenchRoute
  '/catalog': typeof CatalogRoute
  '/chat': typeof ChatRouteWithChildren
  '/status': typeof StatusRoute
  '/transparency': typeof TransparencyRoute
  '/models/': typeof ModelsIndexRoute
  '/chat/$owner/$name': typeof ChatOwnerNameRoute
  '/models/$owner/$name': typeof ModelsOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bench'
    | '/catalog'
    | '/chat'
    | '/status'
    | '/transparency'
    | '/models/'
    | '/chat/$owner/$name'
    | '/models/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bench'
    | '/catalog'
    | '/chat'
    | '/status'
    | '/transparency'
    | '/models'
    | '/chat/$owner/$name'
    | '/models/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bench'
    | '/catalog'
    | '/chat'
    | '/status'
    | '/transparency'
    | '/models/'
    | '/chat/$owner/$name'
    | '/models/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BenchRoute: typeof BenchRoute
  CatalogRoute: typeof CatalogRoute
  ChatRoute: typeof ChatRouteWithChildren
  StatusRoute: typeof StatusRoute
  TransparencyRoute: typeof TransparencyRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  ModelsOwnerNameRoute: typeof ModelsOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$owner/$name': {
      id: '/models/$owner/$name'
      path: '/models/$owner/$name'
      fullPath: '/models/$owner/$name'
      preLoaderRoute: typeof ModelsOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$owner/$name': {
      id: '/chat/$owner/$name'
      path: '/$owner/$name'
      fullPath: '/chat/$owner/$name'
      preLoaderRoute: typeof ChatOwnerNameRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatOwnerNameRoute: typeof ChatOwnerNameRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatOwnerNameRoute: ChatOwnerNameRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BenchRoute: BenchRoute,
  CatalogRoute: CatalogRoute,
  ChatRoute: ChatRouteWithChildren,
  StatusRoute: StatusRoute,
  TransparencyRoute: TransparencyRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  ModelsOwnerNameRoute: ModelsOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
